# Generated by Django 4.2.11 on 2026-03-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
