# Generated by Django 4.2.11 on 2026-03-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entry_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral')], default='Regular', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
