# Generated by Django 5.2.12 on 2026-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Hackathon', 'Hackathon'), ('Coding Contest', 'Coding Contest'), ('Workshop', 'Workshop')], max_length=30)),
                ('venue', models.CharField(max_length=200)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('participation_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team'), ('both', 'Both')], default='solo', max_length=10)),
                ('team_size_min', models.IntegerField(default=2)),
                ('team_size_max', models.IntegerField(default=5)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('is_featured', models.BooleanField(default=False)),
                ('eligible_branches', models.JSONField(default=list)),
                ('eligible_years', models.JSONField(default=list)),
                ('allow_mixed_branches', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
