# Generated by Django 5.2.12 on 2026-03-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='participation_type',
            field=models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10),
        ),
    ]
