# Generated by Django 5.2.12 on 2026-03-18 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_alter_contest_participation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
