# Generated by Django 5.2.12 on 2026-03-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contest_organizers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='organizing_branches',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
