# Generated by Django 4.2.11 on 2026-03-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_contest_organizing_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='is_registration_enabled',
            field=models.BooleanField(default=False, help_text='Enable to allow registrations anytime (spot registration)'),
        ),
    ]
